//
//  SecondViewController.swift
//  DCI
//
//  Created by Georgia Tse on 9/24/15.
//  Copyright © 2015 Georgia Tse. All rights reserved.
//

import UIKit

class AppointmentController: UIViewController {
    
    var myProvider: String?
    var myTime: Int = 0
    var myClinic: String?
    
    @IBOutlet weak var curProvider: UILabel!
    @IBOutlet weak var curTime: UILabel!
    @IBOutlet weak var curClinic: UILabel!
    @IBOutlet weak var curDescription: UILabel!
    @IBOutlet weak var curImage: UIImageView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.view.backgroundColor = UIColor(patternImage: UIImage(named: "blueGradient.jpg")!)
        curProvider.text = "Dr. " + myProvider!
        if myTime == 0 {
            curTime.textColor = UIColor.greenColor()
            curTime.text = "On Time"
        }
        else if myTime > 30 {
            curTime.textColor = UIColor.redColor()
            curTime.text = String(myTime) + "min Late"
        }
        else {
            curTime.textColor = UIColor.yellowColor()
            curTime.text = String(myTime) + "min Late"
        }
        curClinic.text = myClinic
        
        var doctorInfo: [String: Array] = [
            "Dr. J. Abbruzzese":["As a medical oncologist at the Duke Cancer Institute, my focus for many years has been on a challenging cancer – pancreatic cancer. We are learning and making progress, and with the collaborations we build with radiation oncologists, surgeons, our imaging colleagues and others, we’re able to do things today that we could not do 10 years ago. I enjoy interacting directly with patients, particularly sharing with them what the pictures of their diseases look like – in my practice we use a lot of scans to show us what we’re dealing with – and then trying to relate that information to patients in an understandable way, and talk about the different options that are available to them. In my spare time I like to run, work in my yard and fish. After doing mostly saltwater fishing when I lived in Houston, I’m looking forward to exploring my fresh water options in this area.","JAbbruzzese.jpg"],
            "Dr. R. Bain":["Palliative care is a relatively new field of medicine that helps patients and families facing serious illness focus on quality of life. A lot involves trying to understand their needs, hopes and goals, and being a presence for them to ask questions. My style is to go in with a gentle touch. A lot of people have misconceptions about what is palliative care and think the worst. So they’re very fearful about what will happen when I see them. I generally just ask questions and get a sense of what is going on and what their worries are, and try to allay a lot of their fears. I’m really here to be their cheerleader and walk the journey with them. My grandfather passed away when I was about 12 from lung cancer, and I saw him and my family suffer through that period of time. It was an influence on my decision to become a doctor and aid the suffering of those with cancer.","RBain.jpg"],
            "Dr. A. Berchuck":["Surgery and management of patients with cancer is very complex and challenging. I enjoy working at Duke because of the breadth and quality of people we have here. I really feel like I’m working with the best when I’m working with my colleagues. I went into obstetrics and gynecology, because I enjoyed working with women patients. Then as a resident, I found that oncology patients were among the most gratifying to take care of because they appreciate so much everything you try to do for them. In high school and college, I was very interested in science and mathematics, and the human body and physiology. In college, meeting different types of people, I realized that I wanted a profession that gave me the opportunity to interact with all different kinds of people. My wife and I moved here 25 years ago and have never regretted it. It’s a great area to live.","ABerchuck.jpg"],
            "Dr. M. Berry":["I am a medical oncologist with over 35 years experience who specializes only in prostate cancer. I am also a prostate cancer survivor. I see patients who are at high risk for prostate cancer, those with newly diagnosed disease, those with PSA-only recurrent cancer, and those men with metastatic disease. I actively participate in clinical trials. I am married, and have five grown children. I am a North Carolina native. My leisure time is spent playing with my Boykin spaniels, gardening, fly fishing, and occasionally playing golf.",".jpg"],
            "Dr. K. Blackwell":["I specialize in the treatment of patients with breast cancer, in particular the treatment of HER2-driven breast cancer and breast cancers that occur in younger women.","KBlackwell.jpg"],
            "Dr. D. Blazer":["I’m a fellowship-trained surgical oncologist who specializes in the surgical management of patients with gastrointestinal malignancies—including soft tissue sarcomas and pancreas, colorectal and gastric cancers. Many of my patients have advanced malignancies and I am always amazed at their resilience. Their determination to fight inspires me to aggressively pursue every surgical option and to study novel techniques to improve surgical outcomes. One of the most important reasons for patients to be treated at Duke is the emphasis on a team-oriented approach to every patient. Nearly every surgical cancer patient is discussed in a multidisciplinary tumor conference in order to assure state of the art care. When I am not in the hospital, my wife and I can be found chasing our two young children or running with our dog.","DBlazer.jpg"],
            "Dr. R. Blitzblau":["No bio provided","RBlitzblau.jpg"],
            "Dr. A. Desjardins":["My primary focus is patient care and clinical research. My clinical research focuses on providing innovative and aggressive therapies to adults with primary brain tumors. I always keep the patient's quality of life foremost in my practice. I completed my residency in adult neurology at the University of Sherbrooke in Quebec. I finished a two-year fellowship in neuro-oncology at The Preston Robert Tisch Brain Tumor Center at Duke. Upon completion of my fellowship in 2005, I joined the Center as faculty. I am a fellow of the Royal College of Physicians of Canada.","ADesjardins.jpg"],
            "Dr. A. Friedman":["What we specialize in at The Preston Robert Tisch Brain Tumor Center is compassionate care – we take care of our patients. It’s complete care. The patients don’t have to go out and find a radiologist. We have the radiation oncologist, the chemotherapy, the surgery, the radiology, we have all kinds of nursing people as well as help getting physical therapy and getting in-the-home assistance. Patients also can expect cutting-edge care because we run such a terrific science program here. I really like working with the patients. No question about it. It’s not that I’m doing some trivial procedure six times a day. When someone comes in with a brain tumor, there’s usually some bonding, and instead of running away from that, I really enjoy it.","AFriedman.jpg"],
            "Dr. H. Friedman":["I am an academic adult and pediatric neuro-oncologist who helps lead The Preston Robert Tisch Brain Tumor Center at Duke. I am the author of more than 500 peer-reviewed articles, reviews, and book chapters, and I have presented extensively at both international and national meetings. I am a committed educator who is a member of the executive and super-executive committees of the Duke University School of Medicine, which are responsible for the recruitment, screening and selection of medical students. I have reviewed grants for the National Institutes of Health for over 15 years, in a spectrum of different study sections. I am the senior editor of CNS Oncology, associate editor for the Neuro-Oncology Section of Cancer, and a reviewer for over 25 academic journals. I serve on the advisory board of a number of organizations, including Voices Against Brain Cancer, the Tug McGraw Foundation, Pinnacle Care, the Pediatric Brain Tumor Foundation, the National Children’s Cancer Society, and the American Brain Tumor Association.","HFriedman.jpg"],
            "Dr. G. Georgiade":["No bio provided","GGeorgiade.jpg"],
            "Dr. R. Greenup":["My decision to pursue breast surgical oncology was based not only on my strong interest in breast cancer as a disease, but also on my goal to provide patient-centered cancer care. The surgical treatment of breast cancer offers many patients choices, and navigating patients and their families through their treatment process differs from many surgical subspecialties. My clinical and research interests focus on young women with breast cancer, and locally advanced breast cancers.","RGreenup.jpg"],
            "Dr. B. Hanks":["It is my personal goal that every patient that we see feels that they are receiving optimal care here at Duke. My focus is to provide each patient with cutting-edge treatments, and to do so in a compassionate and thoughtful manner.","BHanks.jpg"],
            "Dr. D. Harpole":["With over 20 years of experience as a busy general thoracic surgeon, I am referred patients with cancers in the chest and other difficult problems involving all the organs of the chest that are not from cancer. One of the things that attracted me to the field is the long-term relationship with my patients. I tell all my patients that I’m their doctor for life. I see patients for many, many years. Back in 2000, when we had a 26-inch snow here -- it was a Tuesday -- on my clinic day, everyone said no one would come to clinic. But I actually had 23 or 24 patients show up in four-wheel drives. It’s not that I’m such a fabulous doctor that they came to see me. It’s that they are cancer patients and this was their annual visit or their followup. It was important to them. So we were here for them, and they came. I enjoy seeing my patients back 12, 13, 14 years later and learning what they’ve been up to and what their families have been up to. That’s a bond you get in oncology that a lot of other fields don’t have that treat patients then turn them back over to their primary care physicians. We as a team follow people, and I like that.","DHarpole.jpg"],
            "Dr. M. Hartwig":["A significant portion of my practice involves advanced minimally invasive techniques in thoracic surgery to treat diseases such as lung or esophageal cancer. Another part of my clinical practice is spent taking care of patients with severe lung disease, especially those needing lung transplantation. Patients from all over the world come to Duke for lung transplantation. Research demonstrates that experience is very important in taking care of complex medical problems, both on the surgical side and on the medical side. We have one of the largest transplant centers in the world with excellent survival statistics, as well as the shortest wait list time. Instead of the national average which may be four to six months, our patients wait an average of about two weeks. One of the best aspects of being a patient or working at Duke is the people who work here. No matter how challenging the medical problems may be or what problems may arise, I know there’s a world’s expert a phone call away who can help intervene and I know that my patients will be cared for by committed Duke staff from across the hospital.","MHartwig.jpg"],
//            "Dr. L. Havrilesky":["No bio provided","LHavrilesky.jpg"],
//            "Dr. J. Horton":["No bio provided","JHorton.jpg"],
//            "Dr. D. Hsu":["No bio provided","DHsu.jpg"],
//            "Dr. S. Hwang":["Throughout my career, one fundamental principle has guided my approach to patient care. For each patient, I strive to provide the kind of care that I would want for my own family and bring my best expertise, judgment and empathy to guide patients to restore and maintain long-term health. I know that the work that I do isn’t just for the patients who I directly care for, but it affects the whole family. Being a mother and a wife helps bring that perspective to the work I do. I never lose sight of how important it is to treat the whole family and to recognize the effects of disease on it. I believe that Duke offers patients the best and most advanced care that they can get anywhere in the world. I’ve been touched by cancer in my life. Just being on the receiving end of healthcare makes you very sensitive about the things required for the patient to feel like they are getting the best possible care.","SHwang.jpg"],
//            "Dr. A.  Kamal":["I believe that all patients and their caregivers expect and deserve close attention to issues that are affecting their quality of life. As an oncologist (cancer doctor) and palliative medicine physician, I aim to make the experience of going through serious cancer less distressful, adding in an extra layer of support.","AKamal.jpg"],
//            "Dr. C. Kelsey":["I was drawn to the field of oncology because cancer is a terrifying diagnosis for most people. It is one of those health issues that make people very nervous. I find great satisfaction working with cancer patients to help allay their fears and provide the best care possible. For me, it is rewarding to work with individuals who express so much courage in overcoming a difficult diagnosis. It is very rare that a patient comes alone to an appointment. Usually they have a spouse, son or daughter, a brother or sister, or a mother or father accompanying them. I spend a lot of time answering family member’s questions, who often provide a significant amount of care and support for their loved one. My job is to help educate both the patient and the family and to formulate a plan by which we can provide comprehensive care for all of the patient’s needs.","CKelsey.jpg"],
//            "Dr. G. Kimmick":["When people ask me why I became an oncologist, it reminds me that I’m very lucky to be doing what I do to help people. And when they remind me that it must be very difficult, I nod my head because it is -- but it is also incredibly rewarding. We help people during a very difficult time in their life – a cancer diagnosis. As one of my professors in medical school said, “It is a tremendous compliment for someone to come to us for care,” and I try always to remember that. There aren’t many places in the world where there is a top-notch multidisciplinary breast clinic, with medical oncologists, breast surgeons, plastic surgeons, radiation oncologists, radiologists/breast imagers, physical therapists, nutritionists, pharmacists, social workers and psychologists, nurses, and staff working shoulder-to-shoulder to provide the best, individualized care for each patient. We are lucky to provide individualized care to each person we see.","GKimmick.jpg"],
//            "Dr. P. Lee":["I treat all gynecologic cancers including endometrial/uterine, ovarian, cervical, vaginal, and vulvar cancers. I also take care of women who do not have cancer but may need pelvic surgery that is anticipated to be difficult or complicated. My specific surgical areas of expertise include advanced laparoscopic and robotic surgery, fertility-sparing surgery, sentinel lymph node procedures, laser therapy, and complex pelvic surgery. I have a wonderful support staff, and together we believe we provide the best patient-centered care for all of our patients.","PLee.jpg"],
//            "Dr. C. Mantyh":["I am a colorectal surgeon and researcher who has been at Duke for about 25 years. I see patients who have issues with the small bowel, colon, rectum and anus. These issues include benign tumors, cancers, hemorrhoids and fistulas. The best part of my job is operating. The operating room is a special place, where we have been able to put a number of processes in place so things run smoothly and we can give patients the best chance at a good outcome. The fact that you can take a condition, operate and potentially cure a patient is fascinating to me. As a faculty member, I also enjoy when I have the chance to teach residents during the operation. When I am not at work, I enjoy fishing, hiking and playing tennis with my children.","CMantyh.jpg"],
//            "Dr. P. Marcom":["I am a medical oncologist and have dedicated my career to treating breast cancer and assessing individuals and their families for inherited risk of developing cancer. I originally went into medicine because of my interest in its underlying science. While that aspect still fascinates me, I have over time increasingly valued the personal relationships with my patients and the reward of helping them through the challenges associated with a cancer diagnosis. A confluence of personal, family, and professional events led me to pursue treatment of breast cancer and made it impossible for me to do anything else. Breast cancer receives a great deal of attention because it should; it strikes at our humanity in a unique way. When not working, I spend as much time as I can with my wife and two children as possible. We enjoy boating of all types, spending time at the coast, camping, golf, tennis and travelling.","PMarcom.jpg"],
//            "Dr. M. Morse":["No bio provided","MMorse.jpg"],
//            "Dr. P. Mosca":["My primary areas of clinical interest are surgical oncology, general surgery, and palliative surgery. Melanoma and other skin and soft tissue tumors, as well as palliative surgery, are specific areas in which I have particularly strong clinical and research interests. In addition to patient care and research, I am committed to education and training. It is important to me to be accessible, engaged, and thoughtful in my approach to interacting with patients, colleagues, learners, and other stakeholders. For me, a principle guiding force is a deep-seated belief in patient-centered, multidisciplinary, compassionate, state-of-the-art care t! hat aims to serve our community and support the mission and values of Duke Medicine.","PMosca.jpg"],
//            "Dr. M. Onaitis":["I’m a thoracic surgeon who primarily sees lung and esophageal cancer patients, but treats benign esophageal patients as well. I’ve been at Duke for about 20 years and enjoy working at a place with top-notch clinicians doing cutting-edge work. I became a doctor because I was always interested in math and science and had the privilege of shadowing a physician who lived next door to me. The more experience I had with medicine, the more I liked it. I enjoy surgery, because I like the process of identifying problems and then fixing them. The best part of my job is helping patients overcome cancer. Many patients I see arrive feeling anxious, but are surprised with how well they do and how quickly they can bounce back from surgery. Watching that process unfold continues to be extremely inspiring. I’m originally from Pittsburgh, but my family is proud to call North Carolina home.","MOnaitis.jpg"],
//            "Dr. J. Perkins":["I specialize in endocrine neoplasia, which includes thyroid cancers, parathyroid tumors and adrenal tumors, and in general thyroid diseases. Our practice offers a team approach where you can receive many different services in one place to deliver the most comprehensive care. In one day you can visit me, the endocrine surgeon, get any imaging you may need, get a biopsy, etc., depending on your needs. Having a thyroid condition can be quite stressful for patients so I always try to be an active listener and understand what they’re going through. I want them to walk out the door armed with all the information they need to make decisions. I believe that being a physician is a dual partnership with the patient. Outside of work, I like to spend time with my husband and two kids. We’re an active family that enjoys traveling and being outdoors.","JPerkins.jpg"],
//            "Dr. N. Ready":["I am a medical oncologist and researcher who specializes in treating patients with lung cancer and head and neck cancer. I’ve been at Duke for eight years. I first realized I wanted to become a doctor in graduate school, because it gave me the opportunity to practically apply scientific evidence to help others. What I love most about my job is working with our research and clinical staff to come up with new and hopeful therapies for patients. When a patient comes to see me, I look at their past and current medical history, review their lab tests, and then work with a team to figure out which treatment would work best for them. If a patient comes from far away, we try to make sure we can fit in visits with all the relevant specialists before they leave. Outside of work, I enjoy exercising with friends and spending time with my children at their various activities.","NReady.jpg"],
//            "Dr. S. Roman":["I love being a surgeon, and I am passionate about my specialty. I focus on the surgical treatment and cure of diseases that affect organs which make hormones, such as the thyroid gland, parathyroid glands, adrenal glands, and some parts of the endocrine pancreas.I focus on new surgical and minimally invasive techniques that reduce pain, promote faster recovery, and help people return to their lives. I take care of cancer patients as well as those with benign diseases. Patients often visibly improve after treatment; this gives me a great sense of accomplishment and drives me to do more for my patients. Every patient is unique and has a different need. I always try to understand what that need may be and hope that I can meet it. On a personal note, I am a trained opera singer, and I absolutely love music. I always play music in the operating room. I believe it helps everyone focus, and it helps the patients relax.","SRoman.jpg"],
//            "Dr. A. Salama":["I am a medical oncologist who specializes in the treatment of patients with skin cancer. I am part of a team of surgical oncologists, dermatologists, and radiation oncologists who all work together to determine the best treatment approach for each patient. My focus is on treating patients with advanced melanoma, as well as melanoma that is at high risk for recurrence after surgery. We also treat patients with merkel cell carcinoma and advanced basal cell and cutaneous squamous cell carcinoma. We also have a number of clinical trial options available, allowing our patients access to the newest therapies available.","ASalama.jpg"],
//            "Dr. J. Sampson":["I am a neurosurgeon and researcher who specializes in treating brain tumors. I am originally from Canada, but have been in Durham for 25 years. I decided to become a doctor after spending time working with my family practitioner and getting to know patients from visit to visit. As a clinician, I still enjoy seeing that patients who have had a life-threatening disease are now living normal, healthy lives. My practice is focused around patients with brain cancer, either newly diagnosed or recurrent primary or metastatic brain tumors. We are involved with several clinical trials, so treatment can include enrollment in trials of new therapeutic agents (especially oncolytic poliovirus therapy, immunotherapy, vaccines and convection-enhanced delivery). We also evaluate patients with posterior fossa tumors (eg, acoustic neuromas or meningiomas); microvascular decompression surgery for trigeminal neuralgia and hemifacial spasm, pituitary tumors, complex skull-base tumors; radiosurgery; among other neurosurgery pathologies. In my spare time, I enjoy travel and spending time with my family.","JSampson.jpg"],
//            "Dr. R. Scheri":["I am a surgical oncologist and researcher who specializes in treating patients with endocrine tumors. Specifically, I see patients who have thyroid cancers, parathyroid disease, adrenal tumors, melanoma and breast cancer. I’ve been at Duke for seven years. I enjoy taking care of patients with cancers because the amount of trust and faith that they place in their doctors is special. Treating cancers allows you to develop a powerful relationship with a patient and their loved ones in a very short period of time, which is also unique. My favorite part of being a surgeon is seeing a patient with a problem and successfully seeing them through the surgical process. I believe in guiding each patient to their long-term goal based on their specific needs. When I am at home, I enjoy spending time with my family and being active outdoors by running, hiking or gardening.","RScheri.jpg"],
//            "Dr. A. Secord":["My practice and research focuses on patients who have female-specific cancers, such as ovarian, endometrial, cervical, vulvar or vaginal cancer. I offer my patients access to variety of treatments, ranging from surgery to chemotherapy and radiation. My dad was a physician, and my mom was a nurse, so I was exposed to healthcare at an early age. I enjoy my work on female cancers, because it is one of the few subspecialties to blend surgery and chemotherapy. It also gives me the chance to develop strong relationships with my patients, since I get to take care of my patients before and during their surgery, as well as continue to see them for the rest of their lifetime. I’ve found those patients, who have been able to face their diagnosis with unwavering optimism, to be incredibly inspiring. I have three children, so outside of work I spend as much time as I can with my family.","ASecord.jpg"],
//            "Dr. J. Sosa":["As the leader of the endocrine neoplasia diseases group at Duke, my goal is to bring together physicians from many specialties who care for thyroid, parathyroid, and adrenal problems in order to make it easy and convenient for patients. I am an endocrine surgeon and surgical oncologist, and my clinical practice and research are focused around thyroid cancer. I chose this specialty because patients live with their disease, and I look forward to getting to know and follow them over time. I am challenged by operating on many different parts of the body and performing novel techniques, such as minimally invasive parathyroidectomy and posterior retroperitoneoscopic adrenalectomy. While I spend most of my time in the operating room, I also direct clinical trials using new drugs for patients who previously did not have treatment options. Making their hope a reality motivates me to work harder.","JSosa.jpg"],
//            "Dr. G. Vlahovic":["No bio provided","GVlahovic.jpg"],
//            "Dr. M. Wahidi":["I am a lung specialist with training and focus on interventional pulmonology and lung cancer. I use minimally-invasive technology to diagnose spots on the lungs or abnormalities in the breathing tubes. I also help patients struggling to breath because of blockage in their airways due to tumor, inflammation, or foreign objects. I use innovative bronchoscopy techniques to open the blockages. I let my patients decide with me what works best for them after we discuss benefits and risks of each treatment. I am happiest when my patients return to my clinic telling me about their improved breathing and new-found energy to enjoy their family life. I enjoy spending my free time with my family, including chasing after my three young kids.","MWahidi.jpg"],
//            "Dr. K. Westbrook":["No bio provided","KWestbrook.jpg"],
//            "Dr. M. Zenn":["My plastic surgery practice focuses on breast cancer, breast reconstruction, head and neck reconstruction, and cosmetic surgery. I have been a plastic surgeon for over 20 years and have been practicing at Duke since 2000. I am also a tenured full professor. I treat many different kinds of people, ranging from children who may need surgical help to smile or have had facial trauma, to those who have had a mastectomy. Some of my patients simply want what they see in the mirror to match how they feel on the inside. The overarching principle that guides how I deliver care is “treat people the way you would want you or your family members to be treated.” I believe that there isn’t a “one size fits all” solution to most health problems, so the best way for a doctor to deliver the best care is to listen carefully to each patient and get a sense of their unique needs and preferences.","MZenn.jpg"]
        ]
        
        curDescription.text = "No bio for this provider"
        curImage.image = UIImage(named: "defultPhoto.jpg")
        
        if let doctorName = curProvider?.text {
            
            if let curDoctor = doctorInfo[doctorName] {
                
                if (curDoctor.count == 2) {
                    curDescription.text = curDoctor[0]
                    curImage.image = UIImage(named: curDoctor[1])
                }
            }
        }
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
}

